name: CD Pipeline

on:
  pull_request:
    types: [ opened, edited, synchronized ]

jobs:
  deploy-to-gh-pages:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Application
        run: npm run build

      - name: Extract Branch Name
        id: get-branch
        run: |
          RAW_BRANCH="${{ github.head_ref }}"
          CLEAN_BRANCH=$(echo "$RAW_BRANCH" | sed 's/\//-/g')
          echo "branch_folder=$CLEAN_BRANCH" >> $GITHUB_OUTPUT

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          target-folder: preview/${{ steps.get-branch.outputs.branch_folder }}

      - name: Comment Preview Link on PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            🚀 **Preview Deployed Successfully!**
            You can view the live changes for this PR here: 
            https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/preview/${{ steps.get-branch.outputs.branch_folder }}/
          comment_tag: preview_link